version: '3.9'
services:
  app:
    build: .
    command: sh -c "npm run start"
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    environment:
      - DB_HOST:${DB_HOST}
      - DB_USER:${DB_USER}
      - DB_NAME:${DB_NAME}
      - DB_PASS:${DB_PASS}
    volumes:
      - ./webapp:/opt/webapp
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD:${DB_PASS}
      - POSTGRES_USER:${DB_USER}
      - POSTGRES_NAME:${DB_NAME}
