version: '3.9'
services:
  app:
    build: .
    command: yarn start
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/usr
  db:
    image: postgres:latest
    ports:
      - "5432:5432"